! MODULE SET_RK PROVIDES THE KIND TYPE PARAMETER NEEDED TO DEFINE
! THE PRECISION OF A COMPLETE PACKAGE ALONG WITH VALUES
! FOR COMMONLY USED STANDARD PRECISIONS

  Module SET_RK
    Use ISO_FORTRAN_ENV, Only: REAL32, REAL64, REAL128
    Implicit None
    Public :: RK, DP, QP

! PRECISIONS
    Integer, Parameter :: SP = REAL32 ! SINGLE PRECISION
    Integer, Parameter :: DP = REAL64 ! DOUBLE PRECISION
    Integer, Parameter :: QP = REAL128 ! QUADRUPLE PRECISION

! SET THE PRECISION FOR THE WHOLE PACKAGE
    Integer, Parameter :: RK = dp 

! TO CHANGE THE DEFAULT PACKAGE-PRECISION CHANGE
! THE PARAMETER ASSIGNED TO RK ABOVE TO THE REQUIRED
! PRECISION AND RECOMPILE THE COMPLETE PACKAGE.

  End Module
